name: Build Gradle project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-version:
          - 6.7.1
          - 6.8
        agp-version:
          - 4.1.2
          - 4.2.0
        include:
          - gradle-version: 6.7.1
            agp-version: 4.1.2
            expect: fail
          - gradle-version: 6.8
            agp-version: 4.1.2
            expect: success
          - gradle-version: 6.7.1
            agp-version: 4.2.0
            expect: success
          - gradle-version: 6.8
            agp-version: 4.2.0
            expect: success
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle-version }}
      - run: gradle build
        name: "this step should ${{ matrix.expect }}"
        env:
          AGP_VERSION: ${{ matrix.agp-version }}